name: Automated API tests using Postman CLI

on: 
  workflow_dispatch:
  push:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "25769576-b7cf009b-1c35-47cf-8818-16807bffc40b" -e "25769576-8c400f24-9860-4e90-be41-5bd893a20249"
      - name: logout
        run: postman logout ${{ secrets.POSTMAN_API_KEY }}
